#!/usr/bin/env python3
"""Regenerate the state-dependent sections of INVENTORY.md from the guideline files.

INVENTORY has drifted three times because these sections were hand-maintained while
the files underneath changed. Everything between the AUTO markers is generated; the
editorial sections (version watch-list, known issues, absent guidelines) stay by hand.
"""
import datetime
import pathlib
import re

D = pathlib.Path(__file__).resolve().parent.parent
START = "<!-- AUTO:STATUS -->"
END = "<!-- /AUTO:STATUS -->"


def frontmatter(path):
    fm = path.read_text(encoding="utf-8").split("---")[1]

    def g(k, default=""):
        m = re.search(rf"^{k}:\s*(.+)$", fm, re.M)
        return m.group(1).strip().strip('"') if m else default

    return g


rows = []
for f in sorted((D / "guidelines").glob("*.md")):
    g = frontmatter(f)
    text = f.read_text(encoding="utf-8")
    rows.append(dict(
        name=g("name"), file=f.name, ver=g("version"),
        blocks=len(re.findall(r"^### Item", text, re.M)),
        stub=bool(g("item_text")),
        pending="status: pending curation" in text.split("---")[1],
        lic=g("licence"),
    ))

full = [r for r in rows if not r["stub"] and not r["pending"]]
stubs = [r for r in rows if r["stub"]]
pending = [r for r in rows if r["pending"]]

out = [START, "",
       f"*Generated by `tools/mkinventory.py` on {datetime.date.today().isoformat()} — "
       "do not edit by hand.*", "",
       "## Status", "",
       f"**{len(rows)} guidelines.** {len(full)} carry full item text; {len(stubs)} are "
       f"metadata-only because their licence forbids reproducing the items here; "
       f"{len(pending)} await transcription.", "",
       "See the table in [README.md](README.md) for versions, item counts and what each "
       "extends.", ""]

if stubs:
    out += ["### Metadata only — licence forbids reproducing the items", "",
            "| Guideline | Licence | File |", "|---|---|---|"]
    for r in sorted(stubs, key=lambda x: x["name"].lower()):
        out.append(f"| {r['name']} | {r['lic']} | `guidelines/{r['file']}` |")
    out.append("")

if pending:
    out += ["### Metadata only — item text still to transcribe", "",
            "| Guideline | Version | File |", "|---|---|---|"]
    for r in sorted(pending, key=lambda x: x["name"].lower()):
        out.append(f"| {r['name']} | {r['ver']} | `guidelines/{r['file']}` |")
    out.append("")
else:
    out += ["Every guideline that is present and permitted carries full item text — "
            "nothing is awaiting transcription.", ""]

out.append(END)

p = D / "INVENTORY.md"
t = p.read_text(encoding="utf-8")
if START in t and END in t:
    t = re.sub(re.escape(START) + r".*?" + re.escape(END), "\n".join(out), t, flags=re.S)
else:  # first run: replace the old hand-written status sections
    t = re.sub(r"## Present, complete\n.*?(?=### Extension checklists)",
               "\n".join(out) + "\n\n", t, flags=re.S)
p.write_text(t, encoding="utf-8")
print(f"INVENTORY status regenerated — {len(rows)} guidelines, "
      f"{len(full)} full, {len(stubs)} licence-stubbed, {len(pending)} pending")
